config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'static_pages#home'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'editors#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :editors

end

app/models/editor.rb
class Editor < ActiveRecord::Base
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 8 }, 
                         allow_nil: true
    
    # Returns the hash digest of the given string.
    def Editor.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    #Returns a random token
    def Editor.new_token
        SecureRandom.urlsafe_base64
    end
    
    #Remembers a user in the db for use in persistent sessions
    def remember
        self.remember_token = Editor.new_token
        update_attribute(:remember_digest, Editor.digest(remember_token))
    end
    
    #Returns true if the given token matches the digest
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    #Forget an editor
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_variant
  
  private
    
    #Return the right partial based on user_agent and logged editor (if any)
    def set_variant
      return request.variant = :desktop unless browser.mobile?
    end
    
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  before_action :logged_in_editor
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,   only: :destroy
  
  def show
    @editor = Editor.find(params[:id])
  end
  
  def index
    @editors = Editor.all
  end
  
  def new
    @editor = Editor.new
  end
  
  def create
    @editor = Editor.new(editor_params)
    if @editor.save
      flash[:success] = "Editor added"
      #just for now, then will redirect to home+editor partials
      redirect_to @editor
    else
      render 'new'
    end
  end
  
  def edit
    @editor = Editor.find(params[:id])
  end
  
  def update
    @editor = Editor.find(params[:id])
    if @editor.update_attributes(editor_params)
      flash[:success] = "Profile updated"
      redirect_to @editor
    else
      render 'edit'
    end
  end
  
  def destroy
    Editor.find(params[:id]).destroy
    flash[:success] = "Editor deleted"
    redirect_to editors_url
  end
  
  private
    
    def editor_params
      params.require(:editor).permit(:name, :email, :password,
                                      :password_confirmation)
    end
    
    #Before filters
    
    def logged_in_editor
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
    
    def correct_user
      @editor = Editor.find(params[:id])
      redirect_to(root_url) unless current_editor?(@editor)
    end
    
    def admin_user
      redirect_to(root_url) unless current_editor.admin?
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    editor = Editor.find_by(email: params[:session][:email].downcase)
    if editor && editor.authenticate(params[:session][:password])
      log_in editor
      params[:session][:remember_me] == '1' ? remember(editor) : forget(editor)
      redirect_back_or editor
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #Return the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Agus Jazz Collective"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    #Logs in the giver editor
    def log_in(editor)
        session[:editor_id] = editor.id
    end
    
    #Remembers editor in a persistent session
    def remember(editor)
        editor.remember
        cookies.permanent.signed[:editor_id] = editor.id
        cookies.permanent[:remember_token] = editor.remember_token
    end
    
    #Returns the user corresponding to the remember token cookie
    def current_editor
        if (editor_id = session[:editor_id])
            @current_editor ||= Editor.find_by(id: session[:editor_id])
        elsif (editor_id = cookies.signed[:editor_id])
            editor = Editor.find_by(id: editor_id)
            if editor && editor.authenticated?(cookies[:remember_token])
                log_in editor
                @current_editor = editor
            end
        end
    end
    
    #Returns true if the given editor is the current editor
    def current_editor?(editor)
        editor == current_editor
    end
    
    #Returns true if the editor is logged in, false otherwise
    def logged_in?
        !current_editor.nil?
    end
    
    #Forgets a persistent session
    def forget(editor)
        editor.forget
        cookies.delete(:editor_id)
        cookies.delete(:remember_token)
    end
    
    #Logs out the current editor
    def log_out
        forget(current_editor)
        session.delete(:editor_id)
        @current_editor = nil
    end
    
    #Redirects to stored location (or to the default)
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    #Stores the URL trying to be accessed
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/editors/edit.html.erb
<% provide(:title, "Edit editor") %>
<h1>Update your info </h1>

    <%= form_for(@editor) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes" %>
    <% end %>

app/views/editors/index.html.erb
<% provide(:title, 'All editors') %>
<h1>All editors</h1>

<ul>
  <% @editors.each do |editor| %>
    <li></li>
      <%= link_to editor.name, editor %>
        <% if current_editor.admin? && !current_editor?(editor) %>
            | <%= link_to "delete", editor, method: :delete,
                                            data: { confirm: "You sure?" } %>
        <% end %>
    </li>
  <% end %>
</ul>

app/views/editors/new.html.erb
<% provide(:title, 'Add an editor') %>
<h1>Add an editor for this website</h1>
<%= form_for(@editor) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account" %>
<% end %>

app/views/editors/show.html.erb
<% provide(:title, @editor.name) %>
<h1>
  <%= @editor.name %>
</h1>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
   <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
   </script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert-<%= message_type %>"><%= message %></div>
    <% end %>    
    <%= yield %>
  </div>

  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @editor.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@editor.errors.count, "error") %>.
    </div>
    <ul>
    <% @editor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact us!") %>
<h1>Contact pages!</h1>

app/views/static_pages/home.html+desktop.erb
<% if logged_in? %>
    <%= link_to "Editors", editors_path %>
    <%= link_to "Settings", edit_editor_path(current_editor) %>
    <%= link_to "Log out", logout_path, method: "delete" %>
<% end %>
<div>
    Lorem ipsum desktop
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <%= link_to "Settings", edit_editor_path(current_editor) %>
    <%= link_to "Log out", logout_path, method: "delete" %>
<% end %>
<div class="manifesto">
  <p class="extract">Lorem Ipsum dolor sit amet</p>
</div>
<div class="logo-home">
</div>
<div class="navigation">
  <div class="search">
  </div>
  <div class="facebook">
  </div>
  <div class="contact">
  </div>
  <div class="concerts">
  </div>
  <div class="musicians">
  </div>
  <div class="instruments">
  </div>
</div>